### ISSUE TITLE
Test xarray compatible datasets

### ISSUE THREAD

**Issue by joshmoore** [ome/ZarrReader#35]
Testing the zarr from https://github.com/spatial-image/spatial-image-multiscale/pull/32:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
	at loci.formats.in.ZarrReader.getOptimalTileHeight(ZarrReader.java:130)
	at loci.formats.ImageReader.getOptimalTileHeight(ImageReader.java:753)
	at loci.formats.ReaderWrapper.getOptimalTileHeight(ReaderWrapper.java:585)
	at loci.formats.tools.ImageInfo.readCoreMetadata(ImageInfo.java:577)
	at loci.formats.tools.ImageInfo.testRead(ImageInfo.java:1048)
```
chunks are `[64, 64, 64]`. However, since this dataset follows https://github.com/ome/ngff/pull/114 we might should handle this separately from this PR.

_Originally posted by @joshmoore in https://github.com/ome/ZarrReader/issues/31#issuecomment-1119303509_

**Comment by joshmoore** [comment]
From @dgault:

> Proposed 0.5 changes From Josh's comment https://github.com/ome/ZarrReader/pull/31#issuecomment-1119303509, I have only taken a quick look but this seem like a pretty major breaking change and certainly not for this PR. The metadata appears to have different values for shape and chunks. Currently we are reading the shape values via JZarr.

Also, @thewtex has merged the related PR:
https://github.com/spatial-image/multiscale-spatial-image/pull/32#issuecomment-1135298632
